version: '3.8'

services:
  csv-app:
    container_name: csv-api
    build: .
    command: bash -c "gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always

